### ISSUE TITLE
how to install / use this?

### ISSUE THREAD

**Issue by tomdevlive** [simplistik/acf-ajax-form-submit#2]
Thank you for making this! My only question is how do I implement it? I am running the latest ACF anfd ACFE.

**Comment by simplistik** [comment]
The simplest way to do it would be to add the code from the `functions.php` from this repo into yours, inside your theme. The only thing that the content inside of  `simpl_acf_ajax_submit_form` in this basic example is just checking for the existence of the `acfe_form_front` class, I would argue that this should always exist. [Anything between lines 7 and 10](https://github.com/simplistik/acf-ajax-form-submit/blob/main/functions.php#L7-L10) is can be customized, but it should always end with the `wp_send_json`

In the same way, you'll need to queue the script, in whatever form it's appropriate for your theme. If you already have some javascript in your theme you should be able to probably just[ copy from lines 3 - 68](https://github.com/simplistik/acf-ajax-form-submit/blob/main/script.js#L3-L68) into your own script and it should work. Lines 54 and 57 should be tailored to your needs and how you want to represent your success or failure messages.

I'd have to see how your theme is configured to be able to advise more specifically.
