### ISSUE TITLE
Update post over AJAX

### ISSUE THREAD

**Issue by toniojst** [simplistik/acf-ajax-form-submit#3]
Hi, i succesfuly made code for ajax submitting post. Now i want also made ajax post updating. Everytime when i update my post this make a new post.

**Comment by simplistik** [comment]
@toniojst how are you handling your update form? Are your create forms and update forms separate forms?

**Comment by toniojst** [comment]
Yes, i do separate form. And i find out that even dont work update action without ajax function. So i must fixt this firstly. Can you maybe help me with that?

**Comment by simplistik** [comment]
Can you show me how you have your forms set up? ACFE  should natively be able to detect if it's supposed to be updating or creating.

For instance, here's one that I use:
![image](https://github.com/simplistik/acf-ajax-form-submit/assets/1516830/c50fc5be-a2b9-439c-9cca-84d1bd87f999)

My "Add" form looks like this:
![image](https://github.com/simplistik/acf-ajax-form-submit/assets/1516830/bb68b2e9-3a3f-4de6-a1d3-04fb1841e3d9)

Whereas my "Edit" form looks like this, the most important part of the setup being the `Target` field:
![image](https://github.com/simplistik/acf-ajax-form-submit/assets/1516830/996b7760-d6ea-473f-a518-ef610d25daf4)

**Comment by simplistik** [comment]
@toniojst 

Can you show me how you have your forms set up? ACFE  should natively be able to detect if it's supposed to be updating or creating.

For instance, here's one that I use:
![image](https://github.com/simplistik/acf-ajax-form-submit/assets/1516830/c50fc5be-a2b9-439c-9cca-84d1bd87f999)

My "Add" form looks like this:
![image](https://github.com/simplistik/acf-ajax-form-submit/assets/1516830/bb68b2e9-3a3f-4de6-a1d3-04fb1841e3d9)

Whereas my "Edit" form looks like this, the most important part of the setup being the `Target` field:
![image](https://github.com/simplistik/acf-ajax-form-submit/assets/1516830/996b7760-d6ea-473f-a518-ef610d25daf4)

**Comment by toniojst** [comment]
it look like that i must append manual Post_ID, remove "acf.prepareForAjax" and using my own ajax url "url: MyAjax.ajax_url". Now its working.

![image](https://github.com/simplistik/acf-ajax-form-submit/assets/8342958/fd5e0b31-8c92-4f91-aed3-4784c4559a76)
